services:
  - type: web
    name: buzz-in-server-1
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      set -e
      npm install
      cd client
      npm install
      npm run build
      cd ..
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
