services:
  - type: web
    name: buzz-in-server-1
    env: node
    plan: free
    rootDir: .
   buildCommand: |
  set -e
  npm install
  cd client
  npm install
  npm run build --verbose || echo "CLIENT BUILD FAILED"
  echo "Searching for index.html..."
  find /opt/render/project/src -name "index.html" | tee /opt/render/project/src/build-log.txt
  cd ..
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
